# Pandas
- Data analysis library
- Series      Single Dimension
- Dataframe    Multidimensional

In [1]:
import pandas as pd

# Series

In [2]:
s1 = pd.Series([1,2,4,5,6])
s1

0    1
1    2
2    4
3    5
4    6
dtype: int64

In [3]:
type(s1)

pandas.core.series.Series

In [4]:
s1

0    1
1    2
2    4
3    5
4    6
dtype: int64

In [5]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
s1.values

array([1, 2, 4, 5, 6], dtype=int64)

In [7]:
s3 = pd.Series(range(10))
s3

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [8]:
s4 = pd.Series(range(10,20))
s4

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [9]:
s3 + s4

0    10
1    12
2    14
3    16
4    18
5    20
6    22
7    24
8    26
9    28
dtype: int64

In [10]:
import numpy as np

In [11]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [12]:
arr2 = np.arange(5)
arr2

array([0, 1, 2, 3, 4])

In [13]:
arr1 + arr2

array([0, 2, 4, 6, 8])

# Lamda Function : Anonymus Function (IIF)

In [14]:
new = pd.Series([34,52,63,35, 75 ,100], index= ["Ali","Ahmed","Irfan", "Khan", "Faisal","Hassan"])
new

Ali        34
Ahmed      52
Irfan      63
Khan       35
Faisal     75
Hassan    100
dtype: int64

In [15]:
def myfunc(marks):
    return marks/100

In [16]:
new = new.apply(myfunc)

In [17]:
new.apply(lambda x:x*100 )

Ali        34.0
Ahmed      52.0
Irfan      63.0
Khan       35.0
Faisal     75.0
Hassan    100.0
dtype: float64

In [18]:
new.apply(lambda x:x/100)

Ali       0.0034
Ahmed     0.0052
Irfan     0.0063
Khan      0.0035
Faisal    0.0075
Hassan    0.0100
dtype: float64

In [19]:
new = new.apply(lambda x: np.where(x>50, "Pass","Fail"))

In [20]:
s2 = pd.Series([4,6,2,6,7], index =["apple","banana","guvava","orange","mango"])
s2

apple     4
banana    6
guvava    2
orange    6
mango     7
dtype: int64

In [21]:
s2.index

Index(['apple', 'banana', 'guvava', 'orange', 'mango'], dtype='object')

In [22]:
s4 = pd.Series([6,5,4,6,3], index=s2.index)
s4

apple     6
banana    5
guvava    4
orange    6
mango     3
dtype: int64

In [23]:
s5 = pd.Series(100,index=s2.index)
s5

apple     100
banana    100
guvava    100
orange    100
mango     100
dtype: int64

In [24]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [25]:
new.count()

6

In [26]:
new.value_counts()

Fail    6
dtype: int64

In [27]:
np.random.seed(123456)
s1 = pd.Series(np.random.randn(3))
s2 = pd.Series(np.random.randn(3))

In [28]:
s1

0    0.469112
1   -0.282863
2   -1.509059
dtype: float64

In [29]:
s2

0   -1.135632
1    1.212112
2   -0.173215
dtype: float64

In [30]:
combined = pd.concat([s1,s2])
combined

0    0.469112
1   -0.282863
2   -1.509059
0   -1.135632
1    1.212112
2   -0.173215
dtype: float64

In [31]:
combined.reset_index()

index         0
0      0  0.469112
1      1 -0.282863
2      2 -1.509059
3      0 -1.135632
4      1  1.212112
5      2 -0.173215

In [32]:
combined.reset_index(drop=True)

0    0.469112
1   -0.282863
2   -1.509059
3   -1.135632
4    1.212112
5   -0.173215
dtype: float64

In [33]:
combined[4] = 456
combined

0      0.469112
1     -0.282863
2     -1.509059
0     -1.135632
1      1.212112
2     -0.173215
4    456.000000
dtype: float64

In [34]:
del combined[0]
combined

1     -0.282863
2     -1.509059
1      1.212112
2     -0.173215
4    456.000000
dtype: float64

In [35]:
newCom = combined.copy()
newCom

1     -0.282863
2     -1.509059
1      1.212112
2     -0.173215
4    456.000000
dtype: float64

# Pandas Data Frame

In [36]:
students = {"roll":[1,2,3,4,5,6],
            "name":["Ali","Ahmed","Shazia","Kiran","usman","Amjad"],
            "courses":["python","Pandas","Numpy","pandas","Numpy","JavaS"],
            "mode":["online","online","onsite","online","onsite","online"]}

In [37]:
# Creating a dataframe
df = pd.DataFrame(students)
df

roll    name courses    mode
0     1     Ali  python  online
1     2   Ahmed  Pandas  online
2     3  Shazia   Numpy  onsite
3     4   Kiran  pandas  online
4     5   usman   Numpy  onsite
5     6   Amjad   JavaS  online

In [38]:
type(df["roll"])

pandas.core.series.Series

In [39]:
type(df[["roll","name"]])

pandas.core.frame.DataFrame

In [40]:
# Accressing Data
# Coulmns

In [41]:
df["courses"]

0    python
1    Pandas
2     Numpy
3    pandas
4     Numpy
5     JavaS
Name: courses, dtype: object

In [42]:
df[["courses","name"]]

courses    name
0  python     Ali
1  Pandas   Ahmed
2   Numpy  Shazia
3  pandas   Kiran
4   Numpy   usman
5   JavaS   Amjad

In [43]:
df["country"] = "Pakistan"
df

roll    name courses    mode   country
0     1     Ali  python  online  Pakistan
1     2   Ahmed  Pandas  online  Pakistan
2     3  Shazia   Numpy  onsite  Pakistan
3     4   Kiran  pandas  online  Pakistan
4     5   usman   Numpy  onsite  Pakistan
5     6   Amjad   JavaS  online  Pakistan

In [44]:
df["Ages"] = [22,23, 21,19,20,22]
df

roll    name courses    mode   country  Ages
0     1     Ali  python  online  Pakistan    22
1     2   Ahmed  Pandas  online  Pakistan    23
2     3  Shazia   Numpy  onsite  Pakistan    21
3     4   Kiran  pandas  online  Pakistan    19
4     5   usman   Numpy  onsite  Pakistan    20
5     6   Amjad   JavaS  online  Pakistan    22

In [45]:
df["Status"] = ["Pass" if age>20 else "Fail" for age in df["Ages"]]
df

roll    name courses    mode   country  Ages Status
0     1     Ali  python  online  Pakistan    22   Pass
1     2   Ahmed  Pandas  online  Pakistan    23   Pass
2     3  Shazia   Numpy  onsite  Pakistan    21   Pass
3     4   Kiran  pandas  online  Pakistan    19   Fail
4     5   usman   Numpy  onsite  Pakistan    20   Fail
5     6   Amjad   JavaS  online  Pakistan    22   Pass

In [46]:
df["City"] = df['mode'].apply (lambda x:x)
df

roll    name courses    mode   country  Ages Status    City
0     1     Ali  python  online  Pakistan    22   Pass  online
1     2   Ahmed  Pandas  online  Pakistan    23   Pass  online
2     3  Shazia   Numpy  onsite  Pakistan    21   Pass  onsite
3     4   Kiran  pandas  online  Pakistan    19   Fail  online
4     5   usman   Numpy  onsite  Pakistan    20   Fail  onsite
5     6   Amjad   JavaS  online  Pakistan    22   Pass  online

In [47]:
df["City"] = df['mode'].apply (lambda x:"karachi" if x=="onsite" else "outside khi")
df

roll    name courses    mode   country  Ages Status         City
0     1     Ali  python  online  Pakistan    22   Pass  outside khi
1     2   Ahmed  Pandas  online  Pakistan    23   Pass  outside khi
2     3  Shazia   Numpy  onsite  Pakistan    21   Pass      karachi
3     4   Kiran  pandas  online  Pakistan    19   Fail  outside khi
4     5   usman   Numpy  onsite  Pakistan    20   Fail      karachi
5     6   Amjad   JavaS  online  Pakistan    22   Pass  outside khi

In [48]:
df["City"] = df['mode'].apply (lambda x:np.where(x=="onsite","karachi","outside"))
df

roll    name courses    mode   country  Ages Status     City
0     1     Ali  python  online  Pakistan    22   Pass  outside
1     2   Ahmed  Pandas  online  Pakistan    23   Pass  outside
2     3  Shazia   Numpy  onsite  Pakistan    21   Pass  karachi
3     4   Kiran  pandas  online  Pakistan    19   Fail  outside
4     5   usman   Numpy  onsite  Pakistan    20   Fail  karachi
5     6   Amjad   JavaS  online  Pakistan    22   Pass  outside

In [49]:
def generationAssign(age):
    if age<20:
        return "Teenager"
    elif age<40:
        return "Young"
    elif age<60:
        return "Mature"
    else:
        return "Senior"

In [50]:
df["Generation"] = df.Ages.apply(generationAssign)

In [51]:
df

roll    name courses    mode   country  Ages Status     City Generation
0     1     Ali  python  online  Pakistan    22   Pass  outside      Young
1     2   Ahmed  Pandas  online  Pakistan    23   Pass  outside      Young
2     3  Shazia   Numpy  onsite  Pakistan    21   Pass  karachi      Young
3     4   Kiran  pandas  online  Pakistan    19   Fail  outside   Teenager
4     5   usman   Numpy  onsite  Pakistan    20   Fail  karachi      Young
5     6   Amjad   JavaS  online  Pakistan    22   Pass  outside      Young